- name: Install required packages
  yum: 
    name: "{{ os_packages }}"
    state: present

- name: Clone mysite repo from GitHub
  shell: git clone https://github.com/Zephyr0402/mysite.git

- name: Install Nginx
  yum:
    name: "nginx"
    state: present