- name: Disable selinux
  shell: sudo setenforce 0

- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Copy mysite.service to host
  copy:
    src: ./roles/setup_nginx/defaults/mysite.service
    dest: /etc/systemd/system/mysite.service
    owner: root
    group: root
    mode: '0644'
    
- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Enable & Start mysite.service
  systemd:
    name: mysite.service
    state: started
    enabled: yes

- name: Make sure Nginx is installed
  yum:
    name: nginx
    state: present

- name: Back up Nginx configration
  shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- name: Copy new Nginx configuration to host
  copy:
    src: ./roles/setup_nginx/defaults/nginx.conf
    dest: /etc/nginx
    owner: root
    group: root
    mode: '0644'

- name: Allow the Nginx process to enter and access content
  shell: chmod 710 /home/bevis

- name: Enable & Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes